version: "3"

services:
  sirius-faker:
    ports:
      - 5000:5000
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: "./docker-entrypoint.sh"
    environment:
      - VIRTUAL_HOST=sirius.localhost
